### ISSUE TITLE
Conda/mamba packaging and distribution

### ISSUE THREAD

**Issue by olivhoenen** [iterorganization/IMAS-Python#24]
It was mentioned in https://github.com/iterorganization/IMAS-Python/issues/1 that different packaging could be of interest for some users. If you are interested and have experience with it, help would be appreciated.

**Comment by munechika-koyo** [comment]
I am happy to see this suggestion!
Before I created its conda distribution using [`rattler-build`](https://rattler.build), I will share the associated files which might be messy or become obsolete, though.

I hope this is helpful.

<details>

<summary>recipe.yaml</summary>
This is the base file to build a conda distribution.

```yaml
context:
  version: "5.3.1"
  name: "imas"
  build: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/iterorganization/IMAS-Python/archive/refs/tags/${{ version }}.tar.gz
  sha256: hash value... 

build:
  number: ${{ build }}
  noarch: python
  string: dd${{ data_dictionary | version_to_buildstring }}_pyh${{ hash }}_${{ build }}

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - git
    - cmake
    - ninja
    - saxon-he
    - libxslt
    - pkg-config
  host:
    - pip
    - python ${{ python_min }}.*
    - python-build
    - setuptools
    - imas-core
    - imas-data-dictionary
  run:
    - python >=${{ python_min }}
    - imas-core
    - imas-data-dictionary

tests:
  - python:
      imports:
        - imas
      pip_check: false
  # - script:
  #     - cd tests
  #     - cmake -B build -DAL_BACKEND_HDF5=ON
  #     - cmake -C build install
  #   files:
  #     source:
  #       - tests/
  #   requirements:
  #     run:
  #       - pytest
  #       - cmake
  #       - make

about:
  homepage: https://imas.iter.org/
  license_file: LICENSE.md
  summary: IMAS High Level Interface for Python.
  documentation: https://sharepoint.iter.org/departments/POP/CM/IMDesign/Code%20Documentation/ACCESS-LAYER-doc/python/latest.html
  repository: https://github.com/iterorganization/IMAS-Python.git
```

</details>


<details>

<summary>variants.yaml</summary>
This file contains variants for specific dependencies.

```yaml
data-dictionary:
  - 3.42.*
  - 4.0.*
#  - any other versions...
```

</details>


<details>
<summary>build.sh</summary>
This file is a build script to create a conda package.

```shell
#!/bin/bash

export AL_COMMON_PATH=$PREFIX/share/common

# Temporary workaround to inject the pypa build options
if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i "" "s/build ./build -w -nx/g" $SRC_DIR/CMakeLists.txt
else
    sed -i "s/build ./build -w -nx/g" $SRC_DIR/CMakeLists.txt
fi

# CMake extra configuration:
extra_cmake_args=(
    -GNinja
    -DCMAKE_INSTALL_LIBDIR=lib
    # Python executable
    -DPython_EXECUTABLE="$PYTHON"
    -DPython3_EXECUTABLE="$PYTHON"
    # No build imas-core
    -DAL_DOWNLOAD_DEPENDENCIES=OFF
    -DAL_DEVELOPMENT_LAYOUT=OFF
    -DAL_PYTHON_BINDINGS=OFF
    -DAL_PLUGINS=OFF
    # No build tests and examples
    -DAL_TESTS=OFF
    -DAL_EXAMPLES=OFF
)

mkdir build && cd build

cmake ${CMAKE_ARGS} "${extra_cmake_args[@]}" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH=$PREFIX \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    $SRC_DIR

# Build
ninja

# Install
$PYTHON -m pip install $SRC_DIR/build/dist/*.whl

```
</details>
